app = "parking-system-api"
primary_region = "iad"

[build]

[env]
  Database__SniHost = "ep-misty-flower-achyyk9e-pooler.sa-east-1.aws.neon.tech"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
