// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParkingSystem.Module.Parking.Infra.Data.EF;

#nullable disable

namespace ParkingSystem.Module.Parking.Infra.Data.EF.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    partial class ParkingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("ParkingSystem.Module.Parking.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_saida");

                    b.Property<short?>("FormaPagamento")
                        .HasColumnType("smallint")
                        .HasColumnName("forma_pagamento");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pago");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("placa_veiculo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("VagaId")
                        .HasColumnType("bigint")
                        .HasColumnName("vaga_id");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("PlacaVeiculo");

                    b.HasIndex("VagaId");

                    b.ToTable("movimentacoes", (string)null);
                });

            modelBuilder.Entity("ParkingSystem.Module.Parking.Domain.Entities.Reserva", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataAgendada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_agendada");

                    b.Property<DateTime>("DataLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_limite");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_id");

                    b.Property<long>("VagaId")
                        .HasColumnType("bigint")
                        .HasColumnName("vaga_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VagaId");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("ParkingSystem.Module.Parking.Domain.Entities.Tarifa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<short>("TipoVaga")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_vaga");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_diaria");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_hora");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_mensal");

                    b.Property<DateTime?>("VigenteAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_ate");

                    b.HasKey("Id");

                    b.ToTable("tarifas", (string)null);
                });

            modelBuilder.Entity("ParkingSystem.Module.Parking.Domain.Entities.Vaga", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("TipoVaga")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_vaga");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("vagas", (string)null);
                });

            modelBuilder.Entity("ParkingSystem.Module.Parking.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("ParkingSystem.Module.Parking.Domain.Entities.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .IsRequired();

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("ParkingSystem.Module.Parking.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("ParkingSystem.Module.Parking.Domain.Entities.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .IsRequired();

                    b.Navigation("Vaga");
                });
#pragma warning restore 612, 618
        }
    }
}
